config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cottages#index"
  resources :cottages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cottage.rb
class Cottage < ApplicationRecord
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cottages_controller.rb
class CottagesController < ApplicationController
  def index
    @cottages = Cottage.all
  end

  def show
    @cottage = Cottage.find(params[:id])
    @marker = 
      {
        lat: @cottage.latitude,
        lng: @cottage.longitude
      }
  end

  def new
    @cottage = Cottage.new
  end

  def create
    @cottage = Cottage.new(cottage_params)
    @cottage.save
    redirect_to cottage_path(@cottage)
  end

  def edit
    @cottage = Cottage.find(params[:id])
    @cottage.photo.attach(params[:photo])
  end

  def update
    @cottage = Cottage.find(params[:id])
    @cottage.update(cottage_params)
    redirect_to cottage_path(@cottage)
  end

  def destroy
    @cottage = Cottage.find(params[:id])
    @cottage.destroy
    redirect_to cottages_path
  end

  private

  def cottage_params
    params.require(:cottage).permit(:name, :address, :description, :price_per_night, :number_of_guests, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cottages/_form.html.erb
<div class="cottage-form">
  <h3>Add Property Listing</h3>
  <%= simple_form_for @cottage do |f| %>
    <%= f.input :name, label: "Title" %>
    <%= f.input :address, label: "Address" %>
    <%= f.input :description, label: "Description" %>
    <%= f.input :number_of_guests, label: "Number of guests:" %>
    <%= f.input :price_per_night, label: "Price per night:" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Create cottage", class: "btn btn-primary", style: "width: 100%" %>
  <% end %>
</div>

app/views/cottages/edit.html.erb
<div class="d-flex flex-column min-vh-100">
  <div class="cottage-form">
    <h3>Edit Property Listing</h3>
    <%= simple_form_for @cottage do |f| %>
      <%= f.input :name, label: "Title" %>
      <%= f.input :address, label: "Address" %>
      <%= f.input :description, label: "Description" %>
      <%= f.input :number_of_guests, label: "Number of guests:" %>
      <%= f.input :price_per_night, label: "Price per night:" %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Confirm", class: "btn btn-primary", style: "width: 100%" %>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/cottages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 my-4">
      <h2>Find your home away</h2>
    </div>
  </div>
</div>

<div class="album">
  <div class="container mb-5">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @cottages.each do |cottage| %>
          <div class="col">
            <div class="cottage-card shadow-sm">
              <div class="cottage-card-image">
                <% if cottage.photo.attached? %>
                  <%= image_tag cottage.photo, class: "img-fluid", width: '100%', height: 'auto' %>
                <% end %>
              </div>
              <div class="cottage-card-body m-3">
                <p class="cottage-card-text fw-bold"><%= cottage.name %></p>
                <p class="cottage-card-text"><i class="fa-solid fa-location-dot" style="color: #5f6a7c;"></i>  <%= cottage.address %></p>
                <div class="d-flex justify-content-between">
                <p><i class="fa-solid fa-users" style="color: #5f6a7c;"></i> <%= cottage.number_of_guests %> guests</p>
                <p>£ <%= cottage.price_per_night %></p>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="cottage-card-actions">
                    <%= link_to "Details", cottage_path(cottage), class: "btn btn-outline-primary" %>
                    <%= link_to "Edit",  edit_cottage_path(cottage), style: "color: #186F65", class: "btn btn-outline-success" %>
                    <%= link_to "Delete", cottage_path(cottage), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, style: "color: #FF0000", class: "btn btn-outline-danger" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
</div>

<%= render "shared/footer" %>

app/views/cottages/new.html.erb
<div class="d-flex flex-column min-vh-100">
  <div class="flex-grow-1">
    <%= render "form", cottage: @cottage %>
  </div>

  <%= render "shared/footer" %>
</div>

app/views/cottages/show.html.erb
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="cottage-show-card mt-5">
        <h3><%= @cottage.name %></h3>
        <p class="d-inline-block text-emphasis mt-3 me-4"><i class="fa-solid fa-location-dot" style="color: #5f6a7c;"></i> <%= @cottage.address %></p>
        <div class="cottage-image">
          <% if @cottage.photo.attached? %>
            <%= image_tag @cottage.photo, width: '100%' %>
          <% end %>
        </div>
      </div>

      <div class="cottage-show-card mt-5">
        <h4>Overview</h4>
        <p>3 bedrooms</p>
        <p><i class="fa-solid fa-users" style="color: #5f6a7c;"></i>  <%= @cottage.number_of_guests %> guests max.</p>
      </div>

      <hr class="solid my-5">
      <div class="cottage-show-card">
        <h4>Description</h4>
        <p><%= @cottage.description %></p>
      </div>

      <hr class="solid my-5">
      <div class="cottage-show-card">
        <h4>Location</h4>
        <div class="map-container mb-5" style="width: 100%; height: 500px;"
          data-controller="map"
          data-map-marker-value="<%= @marker.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>

    <div class="col-4 mt-5">
      <div class="cottage-show-card book-form">
        <h4>Book this cottage</h4>
        <form>
          <div class="form-group mb-2">
            <label for="start-date-label">From: </label>
            <input type="text" class="form-control" id="start-date-label" aria-describedby="startLabel" placeholder="1/10/2023">
          </div>
          <div class="form-group mb-2">
            <label for="end-date-label">To: </label>
            <input type="text" class="form-control" id="end-date-label" aria-describedby="endLabel" placeholder="7/10/2023">
          </div>
          <div class="form-group mb-2">
            <label for="guests">No. of guests</label>
            <input type="guests" class="form-control" id="guests" placeholder="6 guests">
            <div class="form-text d-flex justify-content-between">
              <p>Price per night</p>
              <p>From £<%= @cottage.price_per_night%></p>
            </div>
          </div>
          <button type="submit" class="btn btn-primary" style="width: 100%">Check Availability</button>
        </form>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cityescapes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
  
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <a class="footer-icon mx-2" href="#"><i class="fa-brands fa-facebook"></i></a>
  <a class="footer-icon mx-2" href="#"><i class="fa-brands fa-instagram"></i></a>
  <a class="footer-icon mx-2" href="#"><i class="fa-brands fa-twitter"></i></a>
  <p class="copyright">© CityEscapes 2023</p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon mt-3">
  <div class="container-fluid">
    <div class="navbar-title">
      <p class="fw-bold fs-5 text-body-secondary">CityEscapes</p>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/cottages", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Cottage", new_cottage_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "profile.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Guest", "#", class: "dropdown-item" %>
              <%= link_to "Host", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>